#############################################################################
# Makefile for building: ../../../bin/graphics.app/Contents/MacOS/graphics
# Generated by qmake (2.01a) (Qt 4.8.6) on: Thu Mar 26 21:09:33 2015
# Project:  graphics.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile graphics.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -mmacosx-version-min=10.7 -O2 -arch x86_64 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -O2 -arch x86_64 -FQt3D -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt/4.8.6/mkspecs/unsupported/macx-clang-libc++ -I. -I/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtNetwork.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtNetwork.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtOpenGL.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtOpenGL.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/include -I. -Iincludes -Iincludes/expparser -I/usr/local/Cellar/qt/4.8.6/lib/Qt3D.framework/Versions/1/Headers -I/usr/local/Cellar/qt/4.8.6/include/Qt3D -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers -I. -I. -F/usr/local/Cellar/qt/4.8.6/lib
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -mmacosx-version-min=10.7 -arch x86_64
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/4.8.6/lib -L/usr/local/Cellar/qt/4.8.6/lib -framework Qt3D -framework QtOpenGL -L/usr/local/Cellar/qt/4.8.6/lib -F/usr/local/Cellar/qt/4.8.6/lib -framework QtGui -framework QtCore -framework QtNetwork -framework OpenGL -framework AGL 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.7

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = GLView.cpp \
		main.cpp \
		RCube.cpp \
		SceneStateData.cpp \
		includes/CanvasDataGenerator.cpp \
		includes/CanvasState.cpp \
		includes/CanvasStateData.cpp \
		includes/CanvasText.cpp \
		includes/FunctionInputWindow.cpp \
		includes/Line.cpp \
		includes/MainCanvas.cpp \
		includes/MathFunction.cpp \
		includes/Point.cpp \
		includes/Range.cpp \
		includes/widget.cpp \
		includes/window.cpp \
		includes/expparser/error.cpp \
		includes/expparser/functions.cpp \
		includes/expparser/parser.cpp \
		includes/expparser/variablelist.cpp moc_GLView.cpp \
		moc_CanvasState.cpp \
		moc_FunctionInputWindow.cpp \
		moc_widget.cpp \
		moc_window.cpp
OBJECTS       = GLView.o \
		main.o \
		RCube.o \
		SceneStateData.o \
		CanvasDataGenerator.o \
		CanvasState.o \
		CanvasStateData.o \
		CanvasText.o \
		FunctionInputWindow.o \
		Line.o \
		MainCanvas.o \
		MathFunction.o \
		Point.o \
		Range.o \
		widget.o \
		window.o \
		error.o \
		functions.o \
		parser.o \
		variablelist.o \
		moc_GLView.o \
		moc_CanvasState.o \
		moc_FunctionInputWindow.o \
		moc_widget.o \
		moc_window.o
DIST          = /usr/local/Cellar/qt/4.8.6/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_pre.prf \
		../../../pkg.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt3d.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/include_source_dir.prf \
		graphics.pro
QMAKE_TARGET  = graphics
DESTDIR       = ../../../bin/
TARGET        = ../../../bin/graphics.app/Contents/MacOS/graphics

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile ../../../bin/graphics.app/Contents/PkgInfo ../../../bin/graphics.app/Contents/Resources/empty.lproj ../../../bin/graphics.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_FunctionInputWindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) ../../../bin/graphics.app/Contents/MacOS/ || $(MKDIR) ../../../bin/graphics.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: graphics.pro  /usr/local/Cellar/qt/4.8.6/mkspecs/unsupported/macx-clang-libc++/qmake.conf /usr/local/Cellar/qt/4.8.6/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_pre.prf \
		../../../pkg.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt3d.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/include_source_dir.prf \
		/usr/local/Cellar/qt/4.8.6/lib/QtOpenGL.framework/QtOpenGL.prl \
		/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/QtCore.prl \
		/usr/local/Cellar/qt/4.8.6/lib/QtNetwork.framework/QtNetwork.prl
	$(QMAKE) -o Makefile graphics.pro
/usr/local/Cellar/qt/4.8.6/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.6/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_pre.prf:
../../../pkg.pri:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt3d.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/shared.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/include_source_dir.prf:
/usr/local/Cellar/qt/4.8.6/lib/QtOpenGL.framework/QtOpenGL.prl:
/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/QtCore.prl:
/usr/local/Cellar/qt/4.8.6/lib/QtNetwork.framework/QtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile graphics.pro

../../../bin/graphics.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) ../../../bin/graphics.app/Contents || $(MKDIR) ../../../bin/graphics.app/Contents 
	@$(DEL_FILE) ../../../bin/graphics.app/Contents/PkgInfo
	@echo "APPL????" >../../../bin/graphics.app/Contents/PkgInfo
../../../bin/graphics.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) ../../../bin/graphics.app/Contents/Resources || $(MKDIR) ../../../bin/graphics.app/Contents/Resources 
	@touch ../../../bin/graphics.app/Contents/Resources/empty.lproj
	
../../../bin/graphics.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) ../../../bin/graphics.app/Contents || $(MKDIR) ../../../bin/graphics.app/Contents 
	@$(DEL_FILE) ../../../bin/graphics.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,graphics,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt/4.8.6/mkspecs/unsupported/macx-clang-libc++/Info.plist.app >../../../bin/graphics.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/graphics1.0.0 || $(MKDIR) .tmp/graphics1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/graphics1.0.0/ && $(COPY_FILE) --parents GLView.h RCube.h SceneStateData.h includes/CanvasDataGenerator.h includes/CanvasState.h includes/CanvasStateData.h includes/CanvasText.h includes/CoordinateSystem.h includes/FunctionInputWindow.h includes/Line.h includes/MainCanvas.h includes/MathFunction.h includes/Point.h includes/Range.h includes/widget.h includes/window.h includes/expparser/constants.h includes/expparser/error.h includes/expparser/functions.h includes/expparser/parser.h includes/expparser/variablelist.h .tmp/graphics1.0.0/ && $(COPY_FILE) --parents GLView.cpp main.cpp RCube.cpp SceneStateData.cpp includes/CanvasDataGenerator.cpp includes/CanvasState.cpp includes/CanvasStateData.cpp includes/CanvasText.cpp includes/FunctionInputWindow.cpp includes/Line.cpp includes/MainCanvas.cpp includes/MathFunction.cpp includes/Point.cpp includes/Range.cpp includes/widget.cpp includes/window.cpp includes/expparser/error.cpp includes/expparser/functions.cpp includes/expparser/parser.cpp includes/expparser/variablelist.cpp .tmp/graphics1.0.0/ && $(COPY_FILE) --parents includes/FunctionInputWindow.ui .tmp/graphics1.0.0/ && (cd `dirname .tmp/graphics1.0.0` && $(TAR) graphics1.0.0.tar graphics1.0.0 && $(COMPRESS) graphics1.0.0.tar) && $(MOVE) `dirname .tmp/graphics1.0.0`/graphics1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/graphics1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r ../../../bin/graphics.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_GLView.cpp moc_CanvasState.cpp moc_FunctionInputWindow.cpp moc_widget.cpp moc_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_GLView.cpp moc_CanvasState.cpp moc_FunctionInputWindow.cpp moc_widget.cpp moc_window.cpp
moc_GLView.cpp: RCube.h \
		GLView.h
	/usr/local/Cellar/qt/4.8.6/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ GLView.h -o moc_GLView.cpp

moc_CanvasState.cpp: includes/CanvasStateData.h \
		includes/Line.h \
		includes/Point.h \
		includes/CanvasText.h \
		includes/CanvasState.h
	/usr/local/Cellar/qt/4.8.6/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ includes/CanvasState.h -o moc_CanvasState.cpp

moc_FunctionInputWindow.cpp: includes/window.h \
		includes/CanvasState.h \
		includes/CanvasStateData.h \
		includes/Line.h \
		includes/Point.h \
		includes/CanvasText.h \
		includes/MainCanvas.h \
		includes/CanvasDataGenerator.h \
		includes/MathFunction.h \
		includes/expparser/parser.h \
		includes/expparser/constants.h \
		includes/expparser/error.h \
		includes/expparser/functions.h \
		includes/expparser/variablelist.h \
		includes/Range.h \
		includes/FunctionInputWindow.h
	/usr/local/Cellar/qt/4.8.6/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ includes/FunctionInputWindow.h -o moc_FunctionInputWindow.cpp

moc_widget.cpp: includes/widget.h
	/usr/local/Cellar/qt/4.8.6/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ includes/widget.h -o moc_widget.cpp

moc_window.cpp: includes/CanvasState.h \
		includes/CanvasStateData.h \
		includes/Line.h \
		includes/Point.h \
		includes/CanvasText.h \
		includes/MainCanvas.h \
		includes/CanvasDataGenerator.h \
		includes/MathFunction.h \
		includes/expparser/parser.h \
		includes/expparser/constants.h \
		includes/expparser/error.h \
		includes/expparser/functions.h \
		includes/expparser/variablelist.h \
		includes/Range.h \
		includes/window.h
	/usr/local/Cellar/qt/4.8.6/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ includes/window.h -o moc_window.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_FunctionInputWindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_FunctionInputWindow.h
ui_FunctionInputWindow.h: includes/FunctionInputWindow.ui
	/usr/local/Cellar/qt/4.8.6/bin/uic includes/FunctionInputWindow.ui -o ui_FunctionInputWindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

GLView.o: GLView.cpp GLView.h \
		RCube.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLView.o GLView.cpp

main.o: main.cpp GLView.h \
		RCube.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

RCube.o: RCube.cpp RCube.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RCube.o RCube.cpp

SceneStateData.o: SceneStateData.cpp SceneStateData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SceneStateData.o SceneStateData.cpp

CanvasDataGenerator.o: includes/CanvasDataGenerator.cpp includes/CanvasDataGenerator.h \
		includes/MathFunction.h \
		includes/expparser/parser.h \
		includes/expparser/constants.h \
		includes/expparser/error.h \
		includes/expparser/functions.h \
		includes/expparser/variablelist.h \
		includes/Range.h \
		includes/Point.h \
		includes/Line.h \
		includes/CanvasStateData.h \
		includes/CanvasText.h \
		includes/CoordinateSystem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CanvasDataGenerator.o includes/CanvasDataGenerator.cpp

CanvasState.o: includes/CanvasState.cpp includes/CanvasState.h \
		includes/CanvasStateData.h \
		includes/Line.h \
		includes/Point.h \
		includes/CanvasText.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CanvasState.o includes/CanvasState.cpp

CanvasStateData.o: includes/CanvasStateData.cpp includes/CanvasStateData.h \
		includes/Line.h \
		includes/Point.h \
		includes/CanvasText.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CanvasStateData.o includes/CanvasStateData.cpp

CanvasText.o: includes/CanvasText.cpp includes/CanvasText.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CanvasText.o includes/CanvasText.cpp

FunctionInputWindow.o: includes/FunctionInputWindow.cpp includes/FunctionInputWindow.h \
		includes/window.h \
		includes/CanvasState.h \
		includes/CanvasStateData.h \
		includes/Line.h \
		includes/Point.h \
		includes/CanvasText.h \
		includes/MainCanvas.h \
		includes/CanvasDataGenerator.h \
		includes/MathFunction.h \
		includes/expparser/parser.h \
		includes/expparser/constants.h \
		includes/expparser/error.h \
		includes/expparser/functions.h \
		includes/expparser/variablelist.h \
		includes/Range.h \
		includes/ui_FunctionInputWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FunctionInputWindow.o includes/FunctionInputWindow.cpp

Line.o: includes/Line.cpp includes/Line.h \
		includes/Point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Line.o includes/Line.cpp

MainCanvas.o: includes/MainCanvas.cpp includes/MainCanvas.h \
		includes/CanvasDataGenerator.h \
		includes/MathFunction.h \
		includes/expparser/parser.h \
		includes/expparser/constants.h \
		includes/expparser/error.h \
		includes/expparser/functions.h \
		includes/expparser/variablelist.h \
		includes/Range.h \
		includes/Point.h \
		includes/Line.h \
		includes/CanvasStateData.h \
		includes/CanvasText.h \
		includes/CanvasState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainCanvas.o includes/MainCanvas.cpp

MathFunction.o: includes/MathFunction.cpp includes/MathFunction.h \
		includes/expparser/parser.h \
		includes/expparser/constants.h \
		includes/expparser/error.h \
		includes/expparser/functions.h \
		includes/expparser/variablelist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MathFunction.o includes/MathFunction.cpp

Point.o: includes/Point.cpp includes/Point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Point.o includes/Point.cpp

Range.o: includes/Range.cpp includes/Range.h \
		includes/Point.h \
		includes/Line.h \
		includes/MathFunction.h \
		includes/expparser/parser.h \
		includes/expparser/constants.h \
		includes/expparser/error.h \
		includes/expparser/functions.h \
		includes/expparser/variablelist.h \
		includes/CanvasStateData.h \
		includes/CanvasText.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Range.o includes/Range.cpp

widget.o: includes/widget.cpp includes/widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o includes/widget.cpp

window.o: includes/window.cpp includes/CanvasState.h \
		includes/CanvasStateData.h \
		includes/Line.h \
		includes/Point.h \
		includes/CanvasText.h \
		includes/window.h \
		includes/MainCanvas.h \
		includes/CanvasDataGenerator.h \
		includes/MathFunction.h \
		includes/expparser/parser.h \
		includes/expparser/constants.h \
		includes/expparser/error.h \
		includes/expparser/functions.h \
		includes/expparser/variablelist.h \
		includes/Range.h \
		includes/FunctionInputWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o includes/window.cpp

error.o: includes/expparser/error.cpp includes/expparser/error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o error.o includes/expparser/error.cpp

functions.o: includes/expparser/functions.cpp includes/expparser/error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o functions.o includes/expparser/functions.cpp

parser.o: includes/expparser/parser.cpp includes/expparser/parser.h \
		includes/expparser/constants.h \
		includes/expparser/error.h \
		includes/expparser/functions.h \
		includes/expparser/variablelist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser.o includes/expparser/parser.cpp

variablelist.o: includes/expparser/variablelist.cpp includes/expparser/variablelist.h \
		includes/expparser/constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o variablelist.o includes/expparser/variablelist.cpp

moc_GLView.o: moc_GLView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GLView.o moc_GLView.cpp

moc_CanvasState.o: moc_CanvasState.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CanvasState.o moc_CanvasState.cpp

moc_FunctionInputWindow.o: moc_FunctionInputWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FunctionInputWindow.o moc_FunctionInputWindow.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

